#!/usr/bin/env bash
 
MAYAQTBUILD="`dirname \"$0\"`" # Relative
export MAYAQTBUILD="`( cd \"$MAYAQTBUILD\" && pwd )`" # Absolutized and normalized
pushd $MAYAQTBUILD
 
export MAYA_LOCATION=/Applications/Autodesk/maya2017
export QTDIR=$MAYA_LOCATION/Maya.app/Contents
export QMAKESPEC=$QTDIR/mkspecs/macx-clang
export INCDIR_QT=$MAYA_LOCATION/include/Qt
export LIBDIR_QT=$QTDIR/MacOS

error=0
if [ ! -f $QMAKESPEC/qmake.conf ];
then
  echo "You need to install qt-5.6.1-mkspecs.tar.gz in $QTDIR/mkspecs !"
  error=1
fi
if [ ! -f $INCDIR_QT/QtCore/qdir.h ];
then
  echo "You need to uncompress $MAYA_LOCATION/devkit/include/qt-5.6.1-include.tar.gz in $INCDIR_QT !"
  error=1
fi
# qt.conf - /Applications/Autodesk/maya2017/Maya.app/Contents/Resources
if [ ! -f $QTDIR/bin/qt.conf ];
then
  echo "You need to copy $QTDIR/Resources/qt.conf in $QTDIR/bin !"
  error=1
fi
 
test=`grep 'Data=$(DEVKIT_LOCATION)' $QTDIR/bin/qt.conf`
if [ -z "$test" ];
then
  echo "You need to edit $QTDIR/bin/qt.conf to use 'Data=\$(DEVKIT_LOCATION)'"
  error=1
fi
test=`grep 'Headers=$(DEVKIT_LOCATION)/include/Qt' $QTDIR/bin/qt.conf`
if [ -z "$test" ];
then
  echo "You need to edit $QTDIR/bin/qt.conf to use 'Headers=\$(DEVKIT_LOCATION)/include/Qt'"
  error=1
fi
test=`grep 'Libraries=$(MAYA_LOCATION)/MacOS' $QTDIR/bin/qt.conf`
if [ -z "$test" ];
then
  echo "You need to edit $QTDIR/bin/qt.conf to use 'Libraries=\$(MAYA_LOCATION)/MacOS'"
  error=1
fi

if [ $error -eq 1 ];
then
    exit
fi
 
export DYLD_LIBRARY_PATH=$QTDIR/MacOS
export DYLD_FRAMEWORK_PATH=$QTDIR/Frameworks
 
export SIPDIR=$MAYAQTBUILD/sip-4.18.1
export PYQTDIR=$MAYAQTBUILD/PyQt5_gpl-5.7
 
export SIP_EXE=$QTDIR/Frameworks/Python.framework/Versions/2.7/bin/sip
export SIP_INCLUDE=$QTDIR/Frameworks/Python.framework/Versions/2.7/include/python2.7

pushd $PYQTDIR
export PATH=$QTDIR/bin:$PATH
$QTDIR/bin/mayapy ./configure.py LIBDIR_QT=$LIBDIR_QT INCDIR_QT=$INCDIR_QT MOC=$QTDIR/bin/moc --sip=$SIP_EXE --sip-incdir=$SIP_INCLUDE -w --no-designer-plugin 
make -j 8
sudo make install
popd

popd
