#!/usr/bin/env bash
 
MAYAQTBUILD="`dirname \"$0\"`" # Relative
export MAYAQTBUILD="`( cd \"$MAYAQTBUILD\" && pwd )`" # Absolutized and normalized
pushd $MAYAQTBUILD
 
export MAYA_LOCATION=/Applications/Autodesk/maya2017
export QTDIR=$MAYA_LOCATION/Maya.app/Contents
export QMAKESPEC=$QTDIR/mkspecs/macx-clang
export INCDIR_QT=$MAYA_LOCATION/devkit/include/Qt
export LIBDIR_QT=$QTDIR/MacOS

error=0
if [ ! -f $QMAKESPEC/qmake.conf ];
then
  echo "You need to install qt-5.6.1-mkspecs.tar.gz in $QTDIR/mkspecs !"
  error=1
fi
if [ ! -f $INCDIR_QT/QtCore/qdir.h ];
then
  echo "You need to uncompress $MAYA_LOCATION/devkit/include/qt-5.6.1-include.tar.gz in $INCDIR_QT !"
  error=1
fi
# qt.conf - /Applications/Autodesk/maya2017/Maya.app/Contents/Resources
if [ ! -f $QTDIR/bin/qt.conf ];
then
  echo "You need to copy $QTDIR/Resources/qt.conf in $QTDIR/bin !"
  error=1
fi
 
test=`grep "Data=../.." $QTDIR/bin/qt.conf`
if [ ! -z "$test" ];
then
  echo "You need to edit $QTDIR/bin/qt.conf to use 'Data=..'"
  error=1
fi
test=`grep "Headers=../../include" $QTDIR/bin/qt.conf`
if [ ! -z "$test" ];
then
  echo "You need to edit $QTDIR/bin/qt.conf to use 'Headers=../../../devkit/include/Qt'"
  error=1
fi
test=`grep "Libraries=../lib" $QTDIR/bin/qt.conf`
if [ ! -z "$test" ];
then
  echo "You need to edit $QTDIR/bin/qt.conf to use 'Libraries =../MacOS'"
  error=1
fi
test=`grep "Plugins = qt-plugins" $QTDIR/bin/qt.conf`
if [ ! -z "$test" ];
then
  echo "You need to edit $QTDIR/bin/qt.conf to use 'Plugins=../qt-plugins'"
  error=1
fi
test=`grep "Translations = qt-translations" $QTDIR/bin/qt.conf`
if [ ! -z "$test" ];
then
  echo "You need to edit $QTDIR/bin/qt.conf to use 'Translations=../qt-translations'"
  error=1
fi
 
for mod in Core Designer DesignerComponents Gui Help Multimedia Network OpenGL Script ScriptTools Sql Svg WebKit Xml XmlPatterns
do
  if [ ! -f $QTDIR/MacOS/libQt5${mod}.dylib ];
  then
    echo "You need to copy a fake Qt5$mod dylib - cp $QTDIR/MacOS/Qt5$mod $QTDIR/MacOS/libQt5${mod}.dylib !"
    #cp $QTDIR/MacOS/Qt5$mod $QTDIR/MacOS/libQt5${mod}.dylib
    error=1
  fi
done

if [ $error -eq 1 ];
then
    exit
fi
 
export DYLD_LIBRARY_PATH=$QTDIR/MacOS
export DYLD_FRAMEWORK_PATH=$QTDIR/Frameworks
 
export SIPDIR=$MAYAQTBUILD/sip-4.18.1
export PYQTDIR=$MAYAQTBUILD/PyQt5_gpl-5.7
 
export SIP_EXE=$QTDIR/Frameworks/Python.framework/Versions/2.7/bin/sip
export SIP_INCLUDE=$QTDIR/Frameworks/Python.framework/Versions/2.7/include/python2.7

pushd $PYQTDIR
export PATH=$QTDIR/bin:$PATH
$QTDIR/bin/mayapy ./configure.py LIBDIR_QT=$LIBDIR_QT INCDIR_QT=$INCDIR_QT MOC=$QTDIR/bin/moc --sip=$SIP_EXE --sip-incdir=$SIP_INCLUDE -w --no-designer-plugin 
make -j 8
sudo make install
popd

popd
