#!/bin/bash

export QTDIR=~/qt-4.7.1
export PATH=~/qt-4.7.1/bin:$PATH
export QMAKESPEC=macx-g++
export DYLD_LIBRARY_PATH=~/qt-4.7.1/lib 

pushd PyQt-mac-gpl-4.9.4
/Applications/Autodesk/maya2013/Maya.app/Contents/bin/mayapy ./configure.py LIBDIR_QT=~/qt-4.7.1/lib INCDIR_QT=~/qt-4.7.1/include MOC=~/qt-4.7.1/bin/moc -w --no-designer-plugin

# See instructions at http://images.autodesk.com/adsk/files/pyqtmaya2013.pdf
#    grep –r warnold ./*
# then go and execute pyqt-2

popd

