#!/bin/bash

export QTDIR=~/qt-4.7.1
export PATH=~/qt-4.7.1/bin:$PATH
export QMAKESPEC=macx-g++
export DYLD_LIBRARY_PATH=~/qt-4.7.1/lib 

pushd PyQt-mac-gpl-4.9.4

make -j 8
sudo make install

for mod in phonon QtCore QtDeclarative QtDesigner QtDesignerComponents QtGui QtHelp QtMultimedia QtNetwork QtOpenGL QtScript QtScriptTools QtSql QtSvg QtWebKit QtXml QtXmPatterns; do sudo find /Applications/Autodesk/maya2013/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.6/site-packages/PyQt4 -name "*so" -exec install_name_tool -change ${mod}.framework/Versions/4/{mod} @executable_path/${mod} {} \;; done;

popd
