#!/bin/bash

QTDIR=~/qt-4.7.1

export CMAKE=~/cmake/CMake-2.8.9.app/Contents/bin/cmake
export QMAKE=~/qt-4.7.1/bin/qmake
export MAYA_LOCATION=/Applications/Autodesk/maya2013
export PYTHON_EXEC=$MAYA_LOCATION/Maya.app/Contents/bin/mayapy
export PYTHON_SITE=$MAYA_LOCATION/Maya.app/Contents/Frameworks/Python.framework
export PYTHON_INC=$PYTHON_SITE/Headers
export PYTHON_LIB=/usr/lib/libpython2.6.dylib

pushd shiboken-1.1.2

mkdir _output
mkdir _build
pushd _build

$CMAKE -DQT_QMAKE_EXECUTABLE=$QMAKE -DBUILD_TESTS=False -DPYTHON_EXECUTABLE=$PYTHON_EXEC -DPYTHON_INCLUDE_DIR=$PYTHON_INC -DPYTHON_LIBRARY=$PYTHON_LIB -DCMAKE_BUILD_TYPE=Release -DENABLE_ICECC=0 -DCMAKE_OSX_SYSROOT=/Developer/SDKs/MacOSX10.6.sdk -DCMAKE_INSTALL_PREFIX=~/shiboken-1.1.2/_output 

make
sudo make install/fast

popd
popd

