#!/usr/bin/env bash
 
MAYAQTBUILD="`dirname \"$0\"`" # Relative
export MAYAQTBUILD="`( cd \"$MAYAQTBUILD\" && pwd )`" # Absolutized and normalized
pushd $MAYAQTBUILD
 
export SIPDIR=$MAYAQTBUILD/sip-4.19.13
export MAYA_LOCATION=/Applications/Autodesk/maya2019

pushd $SIPDIR
$MAYA_LOCATION/Maya.app/Contents/bin/mayapy ./configure.py --arch=x86_64 --sip-module PyQt5.sip 
make
sudo make install
popd

popd
