#!/usr/bin/env bash
 
MAYAQTBUILD="`dirname \"$0\"`" # Relative
export MAYAQTBUILD="`( cd \"$MAYAQTBUILD\" && pwd )`" # Absolutized and normalized
pushd $MAYAQTBUILD
 
export MAYA_LOCATION=/usr/autodesk/maya2015-x64
export QTDIR=$MAYA_LOCATION
export QMAKESPEC=$QTDIR/mkspecs/linux-g++-64
export INCDIR_QT=$MAYA_LOCATION/include/Qt
export LIBDIR_QT=$QTDIR/lib
 
if [ ! -f $QMAKESPEC/qmake.conf ];
then
  echo "You need to install qt-4.8.5-mkspecs.tar.gz in $QTDIR/mkspecs !"
  exit
fi
if [ ! -f $INCDIR_QT/QtCore/qdir.h ];
then
  echo "You need to uncompress $MAYA_LOCATION/include/qt-4.8.5-include.tar.gz in $INCDIR_QT !"
  exit
fi
# qt.conf - /Applications/Autodesk/maya2015/Maya.app/Contents/Resources
if [ ! -f $QTDIR/bin/qt.conf ];
then
  echo "You need to copy $QTDIR/Resources/qt.conf in $QTDIR/bin !"
  exit
fi
 
test=`grep "Headers=../include/Qt" $QTDIR/bin/qt.conf`
if [ -z "$test" ];
then
  echo "You need to edit $QTDIR/bin/qt.conf to use 'Headers=../include/Qt'"
  exit
fi
 
export SIPDIR=$MAYAQTBUILD/sip-4.15.5
export PYQTDIR=$MAYAQTBUILD/PyQt-x11-gpl-4.10.4
 
pushd $PYQTDIR
export PATH=$QTDIR/bin:$PATH
$QTDIR/bin/mayapy ./configure.py LIBDIR_QT=$LIBDIR_QT INCDIR_QT=$INCDIR_QT MOC=$QTDIR/bin/moc -w --no-designer-plugin -g
make -j 8
sudo make install
popd

popd
