#!/bin/bash

export CMAKE=~/cmake/bin/cmake
export QMAKE=/usr/local/Trolltech/Qt-4.7.1/bin/qmake
export MAYA_LOCATION=/usr/autodesk/maya2013-x64
export SHIBOKEN_DIR=~/shiboken-1.1.2/_output/lib/cmake/Shiboken-1.1.2
export CMAKE_C_COMPILER=/opt/gcc412/bin/gcc412
export CMAKE_CXX_COMPILER=/opt/gcc412/bin/g++412
export LD_LIBRARY_PATH=$MAYA_LOCATION/lib

pushd pyside-qt4.8+1.1.2

mkdir _output
mkdir _build
pushd _build

$CMAKE -DQT_QMAKE_EXECUTABLE=$QMAKE -DBUILD_TESTS=False -DCMAKE_BUILD_TYPE=Release -DShiboken_DIR=$SHIBOKEN_DIR -DCMAKE_C_COMPILER=$CMAKE_C_COMPILER -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER -DCMAKE_INSTALL_PREFIX=~/pyside-qt4.8+1.1.2/_output ..

make
sudo make install

pushd $MAYA_LOCATION/lib/python2.6/site-packages
mkdir PySide
pushd PySide
cp ~/pyside-qt4.8+1.1.2/_output/lib/libpyside-python2.6.so.1.1.2 .
ln -s libpyside-python2.6.so.1.1.2 libpyside-python2.6.so.1.1
ln -s libpyside-python2.6.so.1.1 libpyside-python2.6.so
cp ~/pyside-qt4.8+1.1.2/_output/lib/python2.6/site-packages/PySide/* .
popd
popd

sudo echo "/usr/autodesk/maya2013-x64/lib/python2.6/site-packages/PySide" > /etc/ld.so.conf.d/pyside.conf
sudo ldconfig

popd
popd
